### PR TITLE
fix(doc): ECS_CONTAINER_STOP_TIMEOUT

### PR DESCRIPTION
**Pull request by remiflament**
**Issue number:**

None

**Description of changes:**

Fix the doc of ECS_CONTAINER_STOP_TIMEOUT

### CODE REVIEW

**Comment by stockholmux** [comment]
hey @remiflament - thanks for this - definitely a good catch that `ECS_CONTAINER_STOP_TIMEOUT` doesn't map to `ECS_DISABLE_PRIVILEGED`!

I'm unclear, however, that the value is supposed to be in seconds only. 

It looks like [Bottlerocket isn't doing any extra modification of this setting](https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/ecs-agent/ecs.config#L25) and the [ECS agent's test use the `s` suffix on the value (e.g. `60s` instead of just `60`)](https://github.com/aws/amazon-ecs-agent/blob/master/agent/config/config_test.go#L130).

@arnaldo2792 you added this setting, could you clarify if the intended value should be raw seconds or with time units?

**Comment by remiflament** [comment]
Thanks for your reply, it's definitely the number and the suffix as my ECS deployment failed yesterday with just a number... let me fix that PR.

**Comment by remiflament** [comment]
Hello @stockholmux, I changed it to include the suffix. In the AWS documentation, [the default timeout is 30 seconds](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_StopTask.html#:~:text=The%20default%2030%2Dsecond%20timeout%20can%20be%20configured%20on%20the%20Amazon%20ECS%20container%20agent%20with%20the%20ECS_CONTAINER_STOP_TIMEOUT%20variable).
Let me know if it's ok  for you.
Have a nice day

**Review by stockholmux — APPROVED** [review]
LGTM!

**Comment by stockholmux** [comment]
@remiflament Thank you so much for this! I'll get it published in the next couple of days.

**Comment by arnaldo2792** [comment]
@stockholmux , I just saw this, the configured value should include the units. Thanks @remiflament !

**Pull request merged**
