### PR TITLE
Sort patches in package version list

### PR DESCRIPTION
**Pull request by markusboehme**
**Issue number:** n/a

**Description of changes:**  Sort the patches listed in the [package version list](https://bottlerocket.dev/en/os/1.15.x/version-information/packages/1.15.0/). This makes it easier to follow a patch series since patches are grouped (e.g. kernel) or at least in the proper order (e.g. grub).

This does not yet regenerate any of the front matter for the published package version lists. While I'd like to do that eventually (at least for 1.15.x, unless there's opposition), there's another change I'd like to make first, and we'll only have to do that once.

**Terms of contribution:**

By submitting this pull request, I confirm that my contribution is made under
the terms of the licenses outlined in the LICENSE-SUMMARY file.

### CODE REVIEW

**Comment by stockholmux** [comment]
@markusboehme This is great! Could you describe the desired ordering a little better? Maybe an example? I want to make sure understand what you're after specifically.

Sorting in a bash script feels a bit weird to me and asking for some edge cases where the sort might not work exactly as desired. The other options would be to sort in the template or in javascript (both options would be retroactive to all variants without re-running all the build scripts).

**Comment by markusboehme** [comment]
Sure, check e.g. [the 1.15.0 package version list](https://bottlerocket.dev/en/os/1.15.x/version-information/packages/1.15.0/) and the downstream patches we have for `ecs-agent`. They're in an essentially random order (0005, 0002, 0001, 0004 0003, 1001). However, patches apply in sequence (0001, 0002, 0003, 0004, 0005, 1001). Assuming we list the patches in the package version list to show how we modified an upstream package (and how heavily we did so), the patches being sorted helps a great deal.

As it to feeling weird this happens in a bash script, I'm not sure I'm following. The general design of generating the front matter via bash script is not one I came up with. The split, however, seems to work well and the change is in spirit of the one merged in #202, just taking things a bit further. I'd like to avoid introducing JavaScript for something that can be done statically.

**Review by stmcginnis — APPROVED** [review]

**Comment by stockholmux** [comment]
@markusboehme If this is the expected sorting:

Screenshot 2023-09-25 at 9 14 19 AM

then the template change is trivial (adding `sort` to the template) to achieve the same result:

https://github.com/bottlerocket-os/bottlerocket-project-website/pull/283/files

FWIW, this is a static site build time change, so it's retroactive on all previous versions without having to rebuild the data files. I don't have a problem with generating the data via a bash script, but moving sorting into bash script when it's tiny change in the template seems like a more straight forward method that we can modify-as needed later w/o needing to repull and generate the data for all previous release. If there is a big advantage in doing sorting via bash script that I'm not seeing, I'm fine merging your method.

**Comment by markusboehme** [comment]
I followed the existing approach of sorting in script. #283 works for me.

**Pull request closed without merging**
